### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by FraMecca** [schveiguy/dconf2020#1]
Hi, thanks for the code and the presentation.
Can you put the slides in the repo? I didn't find any link on the dconf site nor the youtube video.

**Comment by schveiguy** [comment]
Thanks!

The slides are linked from here: http://dconf.org/2020/online/index.html

The direct URL is here: http://dconf.org/2020/online/slides/steve.pdf

I'll put a link in the README.

**Comment by FraMecca** [comment]
thanks
